name: Build docker image

on:
  push:
    paths:
      - 'lint/**'
      - '.github/workflows/docker.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write # 推送到 GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image (multi-arch not used, single arch)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: lint/Dockerfile
          push: true
          pull: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mtsx-linter:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/mtsx-linter:latest

      - name: Output image tags
        run: |
          echo "Image pushed:"
          echo "  sha: ghcr.io/${{ github.repository_owner }}/mtsx-linter:${{ github.sha }}"
          echo "  latest: ghcr.io/${{ github.repository_owner }}/mtsx-linter:latest"
